# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: roseite
description: RoseiteOS - A completely hermetic, terminal-free, secure study system.
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

modules:
  # שינוי השם והגרסה המוצגים במערכת
  - type: os-release
    properties:
      name: "Roseite"
      pretty-name: "Roseite"
      version: "0.2-Alpha"

  - type: script
    scripts:
      - add-repos.sh

  - type: rpm-ostree
    install:
      - onlyoffice-desktopeditors
      - https://github.com/digimezzo/dopamine/releases/download/v3.0.2/Dopamine-3.0.2.rpm
    remove:
      # דפדפנים וטרמינל (כולל חבילות השפה)
      - firefox
      - firefox-langpacks
      - konsole
      
      # רשת וקישוריות (כולל כל הפלאגינים והשירותים)
      - plasma-nm
      - plasma-nm-vpnc
      - plasma-nm-openvpn
      - plasma-nm-openconnect
      - kde-connect
      - kde-connect-libs
      - kdeconnectd
      - krfb
      - krfb-libs
      
      # כלי מערכת (כולל פלאגינים והתראות)
      - plasma-discover
      - plasma-discover-notifier
      - plasma-discover-kns
      - plasma-discover-flatpak
      - kate
      - kate-plugins
      - kate-krunner-plugin
      - firewall-config
      - kwalletmanager5
      - khelpcenter
      - plasma-welcome
      - kdebugsettings
      - kernel-modules-extra
      - kinfocenter
      - kjournald
      - kjournald-libs
      
      # מנועי קלט (הסרה מוחלטת של סביבת fcitx לפי הטרמינל המקומי)
      - fcitx5
      - fcitx5-libs
      - fcitx5-qt-libfcitx5qt6widgets
      - fcitx5-qt6
      - fcitx5-qt-qt6gui
      - fcitx5-gtk
      - fcitx5-gtk4
      - fcitx5-gtk3
      - fcitx5-qt-libfcitx5qtdbus
      - fcitx5-qt5
      - fcitx5-data
      - fcitx5-lua
      - fcitx5-chinese-addons
      - fcitx5-chinese-addons-data
      - fcitx5-m17n
      - fcitx5-mozc
      - fcitx5-chewing
      - fcitx5-hangul
      - fcitx5-libthai
      - fcitx5-sayura
      - fcitx5-unikey
      - fcitx5-qt
      - fcitx5-configtool
      - kcm-fcitx5
      - libime
      - libime-data
# הסרת חבילות רקעים של פדורה ו-KDE
      - plasma-workspace-wallpapers
      - f43-backgrounds-kde
      - f43-backgrounds-base
      - desktop-backgrounds-compat
      - desktop-backgrounds-kde


  - type: script
    scripts:
      - set-defaults.sh
      - install-zayit.sh
      - hermetic-lock.sh
