name: Build Torah OS
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Image
        # שים לב לאותיות הגדולות - זה מה שגרם לשגיאה הקודמת
        uses: Vanilla-OS/vib-action@v1
        with:
          recipe: 'recipe.yml'
          # כאן אנחנו בונים את האימג' ושומרים אותו מקומית
          tag: 'torah-os:latest'

      - name: Generate ISO
        uses: Vanilla-OS/os-constructor-action@v1
        with:
          # ה-Action הזה לוקח את האימג' שבנינו למעלה והופך אותו ל-ISO
          image: 'torah-os:latest'

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: Torah-OS-ISO
          path: ./*.iso
